export const MENSCOLLECTION_LOADING = "MENSCOLLECTION_LOADING";
export const ADD_MENSCOLLECTION = "ADD_MENSCOLLECTION";
export const MENSCOLLECTION_FAILED = "MENSCOLLECTION_FAILED";

export const WOMENSCOLLECTION_LOADING = "WOMENSCOLLECTION_LOADING";
export const ADD_WOMENSCOLLECTION = "ADD_WOMENSCOLLECTION";
export const WOMENSCOLLECTION_FAILED = "WOMENSCOLLECTION_FAILED";

export const DAILYESSENTIALS_LOADING = "DAILYESSENTIALS_LOADING";
export const ADD_DAILYESSENTIALS = "ADD_DAILYESSENTIALS";
export const DAILYESSENTIALS_FAILED = "DAILYESSENTIALS_FAILED";

export const BLOG_LOADING = "BLOG_LOADING";
export const ADD_BLOG = "ADD_BLOG";
export const BLOG_FAILED = "BLOG_FAILED";

export const ADD_MENSCART = "ADD_MENSCART";
export const DELETE_MENSCART = "DELETE_MENSCART";

export const ADD_WOMENSCART = "ADD_WOMENSCART";
export const DELETE_WOMENSCART = "DELETE_WOMENSCART";

export const ADD_DAILYESSENTIALSCART = "ADD_DAILYESSENTIALSCART";
export const DELETE_DAILYESSENTIALSCART = "DELETE_DAILYESSENTIALSCART";
