export const MENSCOLLECTION_LOADING = "MENSCOLLECTION_LOADING";
export const ADD_MENSCOLLECTION = "ADD_MENSCOLLECTION";
export const MENSCOLLECTION_FAILED = "MENSCOLLECTION_FAILED";

export const WOMENSCOLLECTION_LOADING = "WOMENSCOLLECTION_LOADING";
export const ADD_WOMENSCOLLECTION = "ADD_WOMENSCOLLECTION";
export const WOMENSCOLLECTION_FAILED = "WOMENSCOLLECTION_FAILED";

export const DAILYESSENTIALS_LOADING = "DAILYESSENTIALS_LOADING";
export const ADD_DAILYESSENTIALS = "ADD_DAILYESSENTIALS";
export const DAILYESSENTIALS_FAILED = "DAILYESSENTIALS_FAILED";

export const BLOG_LOADING = "BLOG_LOADING";
export const ADD_BLOG = "ADD_BLOG";
export const BLOG_FAILED = "BLOG_FAILED";
